//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Recuperacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detencione
    {
        public int ID_Detencion { get; set; }
        public Nullable<int> Estudiante_UID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public string Estado { get; set; }
        public string Motivo { get; set; }
        public string Tipo { get; set; }
    }
}
