//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Recuperacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolBDEntities : DbContext
    {
        public SchoolBDEntities()
            : base("name=SchoolBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Detencione> Detenciones { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
    
        public virtual int sp_ActualizarDetencion(Nullable<int> iD_Detencion, Nullable<int> estudiante_UID, Nullable<System.DateTime> fecha, Nullable<int> total, string estado, string motivo, string tipo)
        {
            var iD_DetencionParameter = iD_Detencion.HasValue ?
                new ObjectParameter("ID_Detencion", iD_Detencion) :
                new ObjectParameter("ID_Detencion", typeof(int));
    
            var estudiante_UIDParameter = estudiante_UID.HasValue ?
                new ObjectParameter("Estudiante_UID", estudiante_UID) :
                new ObjectParameter("Estudiante_UID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarDetencion", iD_DetencionParameter, estudiante_UIDParameter, fechaParameter, totalParameter, estadoParameter, motivoParameter, tipoParameter);
        }
    
        public virtual int sp_ActualizarEstudiante(Nullable<int> estudiante_UID, string matricula, string nombre, string curso, string telefono)
        {
            var estudiante_UIDParameter = estudiante_UID.HasValue ?
                new ObjectParameter("Estudiante_UID", estudiante_UID) :
                new ObjectParameter("Estudiante_UID", typeof(int));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cursoParameter = curso != null ?
                new ObjectParameter("Curso", curso) :
                new ObjectParameter("Curso", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarEstudiante", estudiante_UIDParameter, matriculaParameter, nombreParameter, cursoParameter, telefonoParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarDetenciones_Result> sp_ConsultarDetenciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarDetenciones_Result>("sp_ConsultarDetenciones");
        }
    
        public virtual ObjectResult<sp_ConsultarEstudiantes_Result> sp_ConsultarEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarEstudiantes_Result>("sp_ConsultarEstudiantes");
        }
    
        public virtual int sp_InsertarDetencion(Nullable<int> estudiante_UID, Nullable<System.DateTime> fecha, Nullable<int> total, string estado, string motivo, string tipo)
        {
            var estudiante_UIDParameter = estudiante_UID.HasValue ?
                new ObjectParameter("Estudiante_UID", estudiante_UID) :
                new ObjectParameter("Estudiante_UID", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("Total", total) :
                new ObjectParameter("Total", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarDetencion", estudiante_UIDParameter, fechaParameter, totalParameter, estadoParameter, motivoParameter, tipoParameter);
        }
    
        public virtual int sp_InsertarEstudiante(string matricula, string nombre, string curso, string telefono)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cursoParameter = curso != null ?
                new ObjectParameter("Curso", curso) :
                new ObjectParameter("Curso", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertarEstudiante", matriculaParameter, nombreParameter, cursoParameter, telefonoParameter);
        }
    }
}
